quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.http.cors=true
quarkus.http.cors.origins=/.*/

%dev.quarkus.log.category."org.demo".level=DEBUG

%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${PG_USER:postgres}
%prod.quarkus.datasource.password=${PG_PASS:postgres}
# NOTE: IP must be accessible by application when running inside container
%prod.quarkus.datasource.reactive.url=postgresql://${PG_IP:172.17.0.2}:5432/digg
